### ISSUE TITLE
Questions: Dynamically import icons

### ISSUE THREAD

**Issue by razuro** [supertorpe/ionic-vanilla-js#1]
Hi, thanks for the wonderful code. Is there a way to enable the dynamic icons without having to manually load them in main.js?

**Comment by supertorpe** [comment]
Yes, you should:
1) remove (or comment) the IonIcon definition in /src/ionic.js
2) Add the following lines at the end of index.html:
```html
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
```
3) declare the ion-icon tags with the "name" attribute:
```html
<ion-icon slot="start" name="home"></ion-icon>
...
<ion-icon slot="icon-only" name="menu"></ion-icon>
```
4) remove all icon related stuff from main.js

**Comment by razuro** [comment]
I sincerely appreciate your help. Apologies for not being clear enough with my goal. I thought there's a way to use it directly, installed/linked the file from client side, since we installed it using npm, and not having to depends on CDN files.

I did some changes in main.js to dynamic import the icons, the icons are loaded, but it will throw a console error:
![image](https://user-images.githubusercontent.com/1119199/229549123-43062e3b-c5ca-4238-bbaa-bd7f0730a4fd.png)
probably because the stencil/internal function couldn't form a valid path to the icon's svg file.

Here's my main.js for your reference:
```js
import './style.css';
import './ionic';

const importIcon = async iconName => {
  const { default: file } = await import(`/node_modules/@ionic/core/dist/ionic/svg/${iconName}.svg`);
  return file
}

document.addEventListener("DOMContentLoaded", async () => {
  document.querySelectorAll("ion-icon").forEach(async (el) => {
    const iconName = el.getAttribute('name');
    
    if (iconName != null) {
      const iconPath = await importIcon(iconName)
      el.src = iconPath;
    }
  });
});
```

**Comment by supertorpe** [comment]
Ah, ok. Let's change the tag attribute to "data-name":
```html
<ion-icon slot="start" data-name="home"></ion-icon>
<ion-icon slot="icon-only" data-name="menu"></ion-icon>
```
And main.js like this:
```javascript
import './style.css';
import './ionic';

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll('ion-icon').forEach(async (el) => {
    const name = el.getAttribute('data-name');
    if (name != null) {
      const { default: file } = await import(`/node_modules/@ionic/core/dist/ionic/svg/${name}.svg`);
      el.src = file;
    }
  });
});
```
This works in development mode (pnpm dev), but the built version fails loading the icons due to a 404 not found error. It looks for "http://localhost:4173/node_modules/@ionic/core/dist/ionic/svg/home.svg" which, of course, does not exists. This needs more work to make vite copy the icons or whatever... let me know if you make progress with this.

**Comment by razuro** [comment]
Thanks for the speedy reply. OK, I'll spend some time looking into vite config, and see how it goes. This is a good boilerplate for those looking to use ionic without any JS frameworks/libraries. Kudos to you!

**Comment by supertorpe** [comment]
Hi @razuro  , some progress with this:
```javascript
import './style.css';
import './ionic';

const images = import.meta.glob('/node_modules/@ionic/core/dist/ionic/svg/*.svg', { as: 'url' });

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll('ion-icon').forEach((el) => {
    const name = el.getAttribute('data-name');
    if (name != null) {
      images[`/node_modules/@ionic/core/dist/ionic/svg/${name}.svg`]().then((url) => {
        el.src = url;
      });
    }
  });
});
```
This works in both development and production. However, it copies all the icons to the /assets/ dir -although it lazy loads just the needed assets-.
